name: chat_application_socket_io
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  http: ^1.2.2
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  socket_io_client: ^2.0.3+1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  get: ^4.6.6
  flutter_dotenv: ^5.2.1

flutter:
  uses-material-design: true
  assets:
    - .envApp
    - assets/svg/
    - assets/png/
    - assets/avatar/
    
